### ISSUE TITLE
Add to_str method

### ISSUE THREAD

**Issue by mintuhouse** [Angelmmiguel/material_icons#13] opened 2016-03-31 11:22 UTC
`alias_method :to_str, :to_s` in MaterialIcon Class
Rails [safe_join](http://apidock.com/rails/v4.2.1/ActionView/Helpers/OutputSafetyHelper/safe_join) calls to_str on objects passed before they are concatenated

**Comment by Angelmmiguel** [comment] 2016-03-31 14:29
Hello @mintuhouse,

I check the code of [safe_join](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/output_safety_helper.rb#L31) helper:

```ruby
def safe_join(array, sep=$,)
  sep = ERB::Util.unwrapped_html_escape(sep)

  array.flatten.map! { |i| ERB::Util.unwrapped_html_escape(i) }.join(sep).html_safe
end
```

In Rails 4.2, [ERB::Util.unwrapped_html_escape](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/string/output_safety.rb#L36) doesn't call to `to_str` method. It's only perform a `gsub` in strings that not are marked as `html_safe`.

In Rails master [ERB::Util.unwrapped_html_escape](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/string/output_safety.rb#L34) method is different, but I can't find any reference to `to_str` method.

Where do you see `safe_join` is calling `to_str` method?

**Comment by mintuhouse** [comment] 2016-03-31 14:48
Hi @Angelmmiguel 
Sorry, I over looked. I got `can't convert MaterialIcon to String (MaterialIcon#to_str gives MaterialIcon)` in [this line](https://github.com/Fullscreen/bh/blob/master/lib/bh/classes/base.rb#L62)
Just realized that this safe_join is a [custom implementation](https://github.com/Fullscreen/bh/blob/master/lib/bh/classes/base.rb#L81) from the gem 

I feel its still a good thing to have as `[material_icon, some_view_helpers].join` gives above error.

**Comment by Angelmmiguel** [comment] 2016-03-31 15:01
No problem :). What version of Ruby are you using @mintuhouse?

**Comment by mintuhouse** [comment] 2016-03-31 15:10
2.1.8

**Comment by Angelmmiguel** [comment] 2016-03-31 15:27
Okey.

I find this [interesting article](https://gist.github.com/kinopyo/5682347) about the difference between `to_s` and `to_str` methods. I think `MaterialIcons` meets the requirement to implement `to_str`, the purpose of the class is to be represented as `String`.

I will add this functionality for the next release of Material Icons gem. While next version is released, you can use `material_icon.to_s` in these situations because `String` object implements `to_str` method.

**Comment by mintuhouse** [comment] 2016-03-31 15:45
ok. Thanks @Angelmmiguel

**Comment by Angelmmiguel** [comment] 2016-03-31 16:02
I investigate the problem and it comes from the way to declare the icon name. I use a custom `method_missing` to set all non-defined methods as the icon to display:

```ruby
# Undefined method will ref to the icon.
def method_missing(name)
   @icon = clear_icon(name)
    self
end
```

`Array#join` call to `to_str` method that is not defined in `MaterialIcon`. I think Ruby process this case and call `to_s` to return a `String`. `MaterialIcon` returns itself and `join` fails.

**Comment by Angelmmiguel** [comment] 2016-03-31 16:05
I think I will migrate this behaviour to an `icon` method because using `method_missing` is causing some problems.

**Comment by mintuhouse** [comment] 2016-03-31 16:30
But wouldn't that be a backward incompatible change (assuming we won't maintain complete list of allowed icons - in say .yml file)?

**Comment by Angelmmiguel** [comment] 2016-03-31 16:32
Yes, the problem is that change breaks compatibility with older versions. That's the reason I don't change it :)

**Closed** 2017-02-27 17:52 UTC
Labels: bug, easy
