### ISSUE TITLE
Bug, working in Chrome

### ISSUE THREAD

**Issue by Gilbertojpargas94** [Angelmmiguel/material_icons#25] opened 2018-06-09 01:20 UTC
Hello, i had to add  the next sentence in the css file for material icons work in Chrome browser (it only worked in mozilla)

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}

**Comment by Angelmmiguel** [comment] 2018-06-12 07:40
Hello @Gilbertojpargas94,

That CSS code is required and it's [already in the repository](https://github.com/Angelmmiguel/material_icons/blob/master/app/assets/stylesheets/material_icons.css.erb). You can find more information about how to add it to your Rails project in the [CSS section](https://github.com/Angelmmiguel/material_icons#css) of the README file :)

Hope it helps you!

**Comment by Angelmmiguel** [comment] 2018-06-14 16:10
Since the issue is covered in the README file, I'm going to close this issue.

Feel free to open a new one if you have any other question :)

**Closed by Angelmmiguel** 2018-06-14 16:10 UTC
Labels: question
